name: go_react
services:
  go_react_db: 
    container_name: go_react_db
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=go_react
    volumes:
      - go_react_pg_data:/bitnami/postgresql

volumes:
  go_react_pg_data:
    driver: local